kind: Service
apiVersion: v1
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2333
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: gcr.io/sound-arcade-441302-q1/spring-app
          ports:
            - containerPort: 2333
